version: '3.8'

services:
  frontend:
    build:
      context: ./ma-gpro-design-war/
    ports:
      - "80:8080"
    depends_on:
      - mt-gpro-commun

  mt-gpro-commun:
    build:
      context: .
      dockerfile: Dockerfile.mt-gpro-commun
    ports:
      - "8889:8080"
    depends_on:
      - ma-gpro-logistique

  ma-gpro-logistique:
    build:
      context: .
      dockerfile: Dockerfile.ma-gpro-logistique
    ports:
      - "8890:8080"
    depends_on:
      - postgres

 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: commercial-industriel
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
