version: '3.8'

services:
  frontend:
    build:
      context: ./ma-gpro-design-war/
    ports:
      - "80:8080"
    depends_on:
      - backend

  backend:
    build:
      context: .
    ports:
      - "8888:8080"
    depends_on:
      - postgres
 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: commercial-industriel
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data


volumes:
  pg:
    

