---
- name: Installation Docker
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes
        upgrade: yes
        force_apt_get: yes


    - name: Installer les dépendances requises pour Docker
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release


    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name:  Ajouter le référentiel Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Mise à jour de la liste des paquets (nouvelle source ajoutée)
      apt:
        update_cache: yes


    - name: Installer docker
      apt:
        name: "{{item}}"
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    
    
    - name: Démarrer & Activer le service Docker
      service:
        name: docker
        state: started
        enabled: yes


    - name: Vérifier la version de Docker
      command: docker --version
      register: docker_version
      ignore_errors: true

    - debug:
        msg: "La version de Docker installée est {{ docker_version.stdout }}"
      when: docker_version.rc == 0

    - name: Ajouter l'utilisateur actuel au groupe Docker
      command: sudo usermod -aG docker $USER
    




