---
- name: Installation Docker
  hosts: localhost
  become: true

  tasks:
    //- name: Mise à jour des paquets
      //apt:
        //update_cache: yes
       // upgrade: yes


    - name: Installer docker
      apt:
        name: docker.io
        state: present
    
    
    - name: Démarrer & Activer le service Docker
      service:
        name: docker
        state: started
        enabled: yes


    - name: Vérifier la version de Docker
      command: docker --version
      register: docker_version
      ignore_errors: true

    - debug:
        msg: "La version de Docker installée est {{ docker_version.stdout }}"
      when: docker_version.rc == 0

    - name: Ajouter l'utilisateur actuel au groupe Docker
      command: sudo usermod -aG docker $USER
    




