# Utilisation de l'image Nginx officielle comme base
FROM nginx:latest

# Supprimer les fichiers de configuration par défaut de Nginx
RUN rm -rf /etc/nginx/conf.d/*

# Copier les fichiers de votre application Angular dans le répertoire de travail de Nginx
COPY . /usr/share/nginx/html

# Exposer le port 80 sur lequel Nginx écoute par défaut
EXPOSE 80

# Commande par défaut pour démarrer Nginx lorsque le conteneur est lancé
CMD ["nginx", "-g", "daemon off;"]
