# Stage 1

FROM node:18.20.2 as build-step
MAINTAINER asmaabdallah518@gmail.com
RUN mkdir -p /app
WORKDIR /app
COPY . /app
RUN npm install -g @angular/cli
RUN npm install
COPY . /app
RUN npm run build --production

# Stage 2

FROM nginx:1.23.1-alpine
COPY --from=build-step /app/dist/ma-gpro-design-war/ /usr/share/nginx/html
