# Utilisez une image de base contenant Java et Maven
FROM maven:3.8.1-jdk-11 AS build

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le fichier pom.xml pour installer les dépendances
COPY pom.xml .

# Installez les dépendances
RUN mvn dependency:go-offline

# Copiez le reste des fichiers de l'application
COPY src ./src

# Compilez l'application
RUN mvn package -DskipTests

# Utilisez une image de base légère pour exécuter l'application
FROM openjdk:11-jre-slim

# Copiez le fichier JAR compilé dans le conteneur
COPY --from=build /app/target/*.jar /app/application.jar

# Exposez le port sur lequel l'application Spring Boot écoute
EXPOSE 8080

# Commande pour démarrer l'application Spring Boot
CMD ["java", "-jar", "/app/application.jar"]
