FROM maven:3.6.3-openjdk-11-slim AS BUILDER
ARG VERSION=3.5.0.0-SNAPSHOT
WORKDIR /build/
COPY . /build/

# ma-gpro-logistique
COPY pom.xml /build/ma-gpro-logistique/
RUN mvn clean install
# Build the ma-gpro-logistique-rest WAR
RUN mvn clean package -pl ma-gpro-logistique/ma-gpro-logistique-rest

# Utilisez l'image Tomcat officielle comme base
FROM tomcat:9.0.88
# Copiez le WAR dans le répertoire webapps de Tomcat
WORKDIR /opt/
COPY --from=BUILDER /build/ma-gpro-logistique/ma-gpro-logistique-rest/target/ma-gpro-logistique-rest-${VERSION}.war /opt/tomcat/latest/webapps/

# Exposez le port sur lequel Tomcat écoute (par défaut : 8080)
EXPOSE 8080

# Commande par défaut pour démarrer Tomcat lors de l'exécution du conteneur
CMD ["catalina.sh", "run"]
