FROM maven:3.6.3-openjdk-11-slim AS BUILDER
ARG VERSION=3.5.0.0-SNAPSHOT
WORKDIR /build/
COPY . /build/

# mt-gpro-commun
COPY pom.xml /build/mt-gpro-commun/
RUN mvn clean install
# Build the mt-gpro-commun-rest WAR
RUN mvn clean package -pl mt-gpro-commun/mt-gpro-commun-rest

# Utilisez l'image Tomcat officielle comme base
FROM tomcat:9.0.88
# Copiez le WAR dans le répertoire webapps de Tomcat
WORKDIR /opt/
COPY --from=BUILDER /build/mt-gpro-commun/mt-gpro-commun-rest/target/mt-gpro-commun-rest-${VERSION}.war /opt/tomcat/latest/webapps/

# Exposez le port sur lequel Tomcat écoute (par défaut : 8080)
EXPOSE 8080

# Commande par défaut pour démarrer Tomcat lors de l'exécution du conteneur
CMD ["catalina.sh", "run"]
