FROM maven:3.9.6-openjdk-11 as build-step
MAINTAINER asmaabdallah518@gmail.com
RUN mkdir -p /app
WORKDIR /app
COPY .  /app
RUN mvn -Dmaven.test.skip=true clean package

FROM openjdk:11
COPY --from=build-step /app/target/ma-gpro-logistique-rest-3.5.0.0-SNAPSHOT.war app.war
EXPOSE 8080
ENTRYPOINT ["java","-war","app.war"]
